name: nyoba_quiz_app_soalacak
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/image/a.png
  - assets/image/b.png
  - assets/image/c.png
  - assets/image/d.png
  - assets/image/e.png
  - assets/image/h1.png
  - assets/image/h2.png
  - assets/image/h3.png
  - assets/image/h4.png
  - assets/image/h5.png
  - assets/image/hm1.png
  - assets/image/hm2.png
  - assets/image/hm3.png
  - assets/image/hm4.png
  - assets/image/hm5.png
  - assets/image/k1.png
  - assets/image/k2.png
  - assets/image/k3.png
  - assets/image/k4.png
  - assets/image/k5.png
  - assets/image/n10(1).png
  - assets/image/n10(2).png
  - assets/image/n10(3).png
  - assets/image/n10(4).png
  - assets/image/n10(5).png
  - assets/image/n11(1).png
  - assets/image/n11(2).png
  - assets/image/n11(3).png
  - assets/image/n11(4).png
  - assets/image/n11(5).png
  - assets/image/n12(1).png
  - assets/image/n12(2).png
  - assets/image/n12(3).png
  - assets/image/n12(4).png
  - assets/image/n12(5).png
  - assets/image/n13(1).png
  - assets/image/n13(2).png
  - assets/image/n13(3).png
  - assets/image/n13(4).png
  - assets/image/n13(5).png
  - assets/image/n14(1).png
  - assets/image/n14(2).png
  - assets/image/n14(3).png
  - assets/image/n14(4).png
  - assets/image/n14(5).png
  - assets/image/n15(1).png
  - assets/image/n15(2).png
  - assets/image/n15(3).png
  - assets/image/n15(4).png
  - assets/image/n15(5).png
  - assets/image/n16(1).png
  - assets/image/n16(2).png
  - assets/image/n16(3).png
  - assets/image/n16(4).png
  - assets/image/n16(5).png
  - assets/image/n17(1).png
  - assets/image/n17(2).png
  - assets/image/n17(3).png
  - assets/image/n17(4).png
  - assets/image/n17(5).png
  - assets/image/n18(1).png
  - assets/image/n18(2).png
  - assets/image/n18(3).png
  - assets/image/n18(4).png
  - assets/image/n18(5).png
  - assets/image/n19(1).png
  - assets/image/n19(2).png
  - assets/image/n19(3).png
  - assets/image/n19(4).png
  - assets/image/n19(5).png
  - assets/image/n20(1).png
  - assets/image/n20(2).png
  - assets/image/n20(3).png
  - assets/image/n20(4).png
  - assets/image/n20(5).png
  - assets/image/n21(5).png
  - assets/image/n21(1).png
  - assets/image/n21(2).png
  - assets/image/n21(3).png
  - assets/image/n21(4).png
  - assets/image/n21(5).png
  - assets/image/n22(1).png
  - assets/image/n22(2).png
  - assets/image/n22(3).png
  - assets/image/n22(4).png
  - assets/image/n22(5).png
  - assets/image/n23(1).png
  - assets/image/n23(2).png
  - assets/image/n23(3).png
  - assets/image/n23(4).png
  - assets/image/n23(5).png
  - assets/image/n24(1).png
  - assets/image/n24(2).png
  - assets/image/n24(3).png
  - assets/image/n24(4).png
  - assets/image/n24(5).png
  - assets/image/n25(1).png
  - assets/image/n25(2).png
  - assets/image/n25(3).png
  - assets/image/n25(4).png
  - assets/image/n25(5).png
  - assets/image/n26(1).png
  - assets/image/n26(2).png
  - assets/image/n26(3).png
  - assets/image/n26(4).png
  - assets/image/n26(5).png
  - assets/image/n27(1).png
  - assets/image/n27(2).png
  - assets/image/n27(3).png
  - assets/image/n27(4).png
  - assets/image/n27(5).png
  - assets/image/n28(1).png
  - assets/image/n28(2).png
  - assets/image/n28(3).png
  - assets/image/n28(4).png
  - assets/image/n28(5).png
  - assets/image/n29(1).png
  - assets/image/n29(2).png
  - assets/image/n29(3).png
  - assets/image/n29(4).png
  - assets/image/n29(5).png
  - assets/image/n30(1).png
  - assets/image/n30(2).png
  - assets/image/n30(3).png
  - assets/image/n30(4).png
  - assets/image/n30(5).png
  - assets/image/n31(1).png
  - assets/image/n31(2).png
  - assets/image/n31(3).png
  - assets/image/n31(4).png
  - assets/image/n31(5).png
  - assets/image/n32(1).png
  - assets/image/n32(2).png
  - assets/image/n32(3).png
  - assets/image/n32(4).png
  - assets/image/n32(5).png
  - assets/image/n33(1).png
  - assets/image/n33(2).png
  - assets/image/n33(3).png
  - assets/image/n33(4).png
  - assets/image/n33(5).png
  - assets/image/n34(1).png
  - assets/image/n34(2).png
  - assets/image/n34(3).png
  - assets/image/n34(4).png
  - assets/image/n34(5).png
  - assets/image/n35(1).png
  - assets/image/n35(2).png
  - assets/image/n35(3).png
  - assets/image/n35(4).png
  - assets/image/n35(5).png
  - assets/image/p2n16(1).png
  - assets/image/p2n16(2).png
  - assets/image/p2n16(3).png
  - assets/image/p2n16(4).png
  - assets/image/p2n16(5).png
  - assets/image/p2n17(1).png
  - assets/image/p2n17(2).png
  - assets/image/p2n17(3).png
  - assets/image/p2n17(4).png
  - assets/image/p2n17(5).png
  - assets/image/pro1.png
  - assets/image/pro2.png
  - assets/image/pro3.png
  - assets/image/pro4.png
  - assets/image/pro5.png
  - assets/image/soal.png
  - assets/image/soal27.png
  - assets/image/soalbagian3.png
  - assets/image/soalh.png
  - assets/image/soalhm.png
  - assets/image/soalK.png
  - assets/image/soaln5(part 2).png
  - assets/image/soaln10.png
  - assets/image/soaln11.png
  - assets/image/soaln12.png
  - assets/image/soaln14.png
  - assets/image/soaln14(part 2).png
  - assets/image/soaln15 (part 2).png
  - assets/image/soaln16 (p2).png
  - assets/image/soaln17.png
  - assets/image/soaln18p2.png
  - assets/image/soaln19p2.png
  - assets/image/soaln20.png
  - assets/image/soaln20p2.png
  - assets/image/soaln23.png
  - assets/image/soaln26.png
  - assets/image/soaln30.png
  - assets/image/soaln33.png
  - assets/image/soaln34.png
  - assets/image/soaln35.png
  - assets/image/soalp2n17.png
 
